sudo: false
language: php
php:
    - 5.6
    - 5.5
    - 7.0
    - 7.1

before_script:
    - composer selfupdate
    - composer install --prefer-source

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - ./vendor/bin/phpunit
